{% set name = "napari-dexp" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-dexp-{{ version }}.tar.gz
  sha256: 134318fb3ec29d460350148a187be8e2c89f817a2391e79ef1afe38992b11925

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - dexp
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - napari

test:
  imports:
    - napari_dexp
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - oclgrind

about:
  home: https://github.com/royerlab/napari-dexp
  summary: A simple plugin to use with napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JoOkuma
    - goanpeca
    - jaimergp
